version: "3.9"

services:
  django:
    restart: unless-stopped
    volumes: []
    env_file:
      - ./backend/.env.prod
    ports: []
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  celery:
    restart: unless-stopped
    volumes: []
    env_file:
      - ./backend/.env.prod
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  celery_beat:
    restart: unless-stopped
    volumes: []
    env_file:
      - ./backend/.env.prod
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    ports: []
  postgres:
    ports: []